@echo off
REM Batch script to build a release signed APK for MQFTPServer
REM Author: Generated by GitHub Copilot
REM Date: September 9, 2025

setlocal enabledelayedexpansion

echo MQFTPServer Release APK Builder
echo ================================

REM Check if we're in the right directory
if not exist "build.gradle.kts" (
    echo ERROR: build.gradle.kts not found. Please run this script from the project root directory.
    pause
    exit /b 1
)

if not exist "gradlew.bat" (
    echo ERROR: gradlew.bat not found. This script requires Gradle Wrapper.
    pause
    exit /b 1
)

REM Check Java installation
java -version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Java not found in PATH. Please install Java JDK 17 or later.
    pause
    exit /b 1
)

echo Java found.
echo.

REM Get signing information
set /p KEYSTORE_PATH="Enter keystore path (.jks or .keystore file): "
if not exist "%KEYSTORE_PATH%" (
    echo ERROR: Keystore file not found: %KEYSTORE_PATH%
    pause
    exit /b 1
)

set /p KEY_ALIAS="Enter key alias: "

REM Note: Batch doesn't handle password input securely, so we'll use a different approach
echo.
echo WARNING: Passwords will be visible in this batch script.
echo For secure password input, use the PowerShell script instead.
echo.
set /p KEYSTORE_PASSWORD="Enter keystore password: "
set /p KEY_PASSWORD="Enter key password: "

REM Ask if clean build is needed
set /p CLEAN_BUILD="Perform clean build? (y/n): "

echo.
echo Starting build process...

REM Perform clean if requested
if /i "%CLEAN_BUILD%"=="y" (
    echo Performing clean build...
    call gradlew.bat clean
    if errorlevel 1 (
        echo ERROR: Clean failed
        pause
        exit /b 1
    )
)

REM Build release APK with signing
echo Building release APK with signing...
call gradlew.bat assembleRelease ^
    "-PRELEASE_STORE_FILE=%KEYSTORE_PATH%" ^
    "-PRELEASE_STORE_PASSWORD=%KEYSTORE_PASSWORD%" ^
    "-PRELEASE_KEY_ALIAS=%KEY_ALIAS%" ^
    "-PRELEASE_KEY_PASSWORD=%KEY_PASSWORD%"

if errorlevel 1 (
    echo ERROR: Build failed
    pause
    exit /b 1
)

echo.
echo Build successful!

REM Find the generated APK
for %%f in ("app\build\outputs\apk\release\*.apk") do (
    echo.
    echo APK Generated Successfully!
    echo ===========================
    echo Location: %%~ff
    
    REM Get file size
    for %%a in ("%%f") do set size=%%~za
    set /a sizeMB=!size!/1024/1024
    echo Size: !sizeMB! MB
    
    REM Copy to project root with timestamp
    for /f "tokens=1-4 delims=/ " %%a in ('date /t') do set mydate=%%c%%a%%b
    for /f "tokens=1-2 delims=: " %%a in ('time /t') do set mytime=%%a%%b
    set timestamp=!mydate!!mytime: =!
    set projectApkName=MQFTPServer-release-!timestamp!.apk
    copy "%%f" "!projectApkName!" >nul
    echo APK also copied to: %CD%\!projectApkName!
    
    goto :found
)

echo WARNING: APK file not found in expected location
:found

echo.
echo Build process completed successfully!
echo You can now install the APK on your device or publish it to app stores.
echo.
pause
